In [4]:
import numpy as np

### Convert a list into a numpy array

In [6]:
lista = [1, 4 , 7, 0.6, 9]
array = np.array(list)

print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
# I want to create a 1d array

array1 = np.array([1,2,3,4,5])
print(array1)


[1 2 3 4 5]


In [10]:
type(array1) #<---data structure

array1.dtype #<--- data type

dtype('int32')

In [20]:
array1.ndim #<--- dimension of an array

1

In [22]:
# I want to create a 2d array

array2 = np.array([[1,2,3,4,5]])
print(array2.ndim)
print(array2)

2
[[1 2 3 4 5]]


In [26]:
print(array1.shape)
print(array2.shape)

(5,)
(1, 5)


In [32]:
array3 = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]], dtype = np.float32)

In [34]:
print(array3.shape)
print(array3.ndim)
print(array3.dtype)

(3, 3)
2
float32


In [36]:
array4 = np.array([[1],[2],[3],[4],[5]])
print(array4.shape)
print(array4.ndim)

(5, 1)
2


### Ways to create arrays

In [40]:
# 1) np.arange(inizio, fine + 1, passo) (Array of range)
arange_arr = np.arange(1,10, 1)
print(arange_arr)

[1 2 3 4 5 6 7 8 9]


In [42]:
reshaped_array = arange_arr.reshape(3, 3)
print(reshaped_array)

reshaped_array.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]


dtype('int32')

In [44]:
# Convert this into a float32 data type
reshaped_array_float = reshaped_array.astype(np.float32)
print(reshaped_array_float.dtype)

float32


In [94]:
# 2) linspace(inizio, fine, numero_di_elementi)
array_lin = np.linspace(1, 4, 5)
print(array_lin)
print(array_lin.dtype)
array_lin_float32 = array_lin.astype(np.float32)
print(array_lin_float32.dtype)

[1.   1.75 2.5  3.25 4.  ]
float64
float32


In [64]:
# 3) np.zeros(shape, DataType)  --> può essere utilizzato per inizializzare un array di zero
zeros_array_int8 = np.zeros(2,"int8")
print("zeros_array_int8 =", zeros_array_int8)
print("\n")

zeros_array = np.zeros((2,2), np.int8)
print(zeros_array)
print(zeros_array.dtype)

zeros_array_int8 = [0 0]


[[0 0]
 [0 0]]
int8


In [79]:
# 4) ones(shape, DataType) --> Array di uno
ones_array_int8 = np.ones((3,3),"int8")
print(ones_array_int8)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Random module of NumPy
- Random.Rand
- Random.Randint
- Seed Value

Let's create arrays of random numbers

In [112]:
# Array of random numbers between 0 (incl) and 1 (excl)
random_array = np.random.rand(1,2) # rand((shape))
print(random_array)

[[0.88030176 0.14180787]]


In [114]:
# Array of random integer numbers (low inclused and high excluded)
random_array_int = np.random.randint(low = 2, high = 11, size = (2,2))
print(random_array_int)

[[7 8]
 [9 5]]


In [122]:
# Random.seed -> Fix an array with the same type of randomness
np.random.seed(5)
random_array_int = np.random.randint(low = 2, high = 11, size = (2,2))
random_array_int

array([[5, 8],
       [8, 2]])